package com.eve.dao;
import java.util.List;

import com.eve.dto.DishDto;
import com.eve.dto.OrderDto;
import com.eve.entity.*;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface dishMapper{


    Dish selectByPrimaryKey(long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_DISH
     *
     * @mbg.generated
     */
    List<DishDto> selectAll();
    
    /*'
     *  add dish to dish table 
     *  parameter dish (long: id   string:name  description price type)
     */
    void insert(Dish dish);
    /*
     * change the dish price 
     * parameter long :id     double:price 
     */
    void changePrice(@Param("id")long id, @Param("price")double price);
    
    long searchTypeID(String typeName) ;
		// TODO Auto-generated method stub
    
    void insertList(@Param("dishes")List<Dish> dishes);
    
    void getRoom(Order order);
    
    int check(long roomId);
    
    long checkOrderId(long roomId);
    
    void orderDishes(@Param("orderItem")List<OrderItem> orderItem);
    
    long freshPrice(long orderId);
    
    Order brief(long roomId);
    
    void freshPrice_table(@Param("totalPrice")long totalPrice, @Param("orderId")long orderId);
    
    List<Dish> checkDishes(long roomId);
    
    OrderDto detail(long roomId);
    OrderDto test(long roomId);
    
}
 