package com.eve.entity;

public class OrderItem {

    private Long id;

    private Long orderId;

    private Long dishId;


    private Boolean state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TR_ORDER_ITEM.ID
     *
     * @return the value of TR_ORDER_ITEM.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }


    public Long getOrderId() {
        return orderId;
    }

    public void setOrderId(Long long1) {
        this.orderId = long1;
    }


    public Long getDishId() {
        return dishId;
    }


    public void setDishId(Long dishId2) {
        this.dishId = dishId2;
    }

    public Boolean getState() {
        return state;
    }

    public void setState(Boolean state) {
        this.state = state;
    }
}